### ISSUE TITLE
README should note that this architecture differs from what is suggested in the documentation

### ISSUE THREAD

**Issue by juansb827** [NarHakobyan/awesome-nest-boilerplate#10]
I think this architecture differs from what is **implicitly** suggested in the NestJS documentation, i don't think this is a bad thing as every architecture has its pros and cons. But i think it should be noted in the README.

For example if you want to work with some feature related with cats, you would have to navigate through several folders (middleware, interfaces, providers, etc...). 

In the Nestjs documentation,  files are close to their domain, so you have everything you need in one place. For instance, there is Cats Folder, containing everything related to cats. 

![image](https://user-images.githubusercontent.com/8711336/65703403-52087b00-e04a-11e9-949c-a33491fe6cb5.png)
Taken from [https://docs.nestjs.com/modules](https://docs.nestjs.com/modules)

**Comment by NarHakobyan** [comment]
@juansb827 Hi, I suggest you check modules directory
![image](https://user-images.githubusercontent.com/1781506/65769981-1bb02600-e146-11e9-943b-faac7871753d.png)

**Comment by NarHakobyan** [comment]
yeah, I need to write a lot of docs :D

**Comment by juansb827** [comment]
Oh, thank you for the clarification!
