### ISSUE TITLE
Change default functions to arrow functions

### ISSUE THREAD

**Issue by pietrzakadrian** [NarHakobyan/awesome-nest-boilerplate#11]
since we are using the latest js standards, can you change the style of function creation to arrows?

`    async createUser(userRegisterDto: UserRegisterDto): Promise<UserEntity> {...}`

change to

`    createUser = async (userRegisterDto: UserRegisterDto): Promise<UserEntity> => {...}`

**Comment by NarHakobyan** [comment]
Hi @pietrzakadrian.
Sorry, but it does not correspond to our linter standards. It's very good to use arrow functions for callbacks, or for function expressions but not for call methods.
