### ISSUE TITLE
send token to protected api

### ISSUE THREAD

**Issue by farshidinanloo** [NarHakobyan/awesome-nest-boilerplate#116]
I'm trying to send access token in this way but it show unauthorized massage
can you tell me how should I send access token? 

![1](https://user-images.githubusercontent.com/46605967/145604067-ba36006f-b582-4a3d-9b1d-779aeee2e643.PNG)

**Comment by NarHakobyan** [comment]
you are using invalid token,

![image](https://user-images.githubusercontent.com/1781506/147860142-76e0a52c-8d61-4f7b-bb99-a35028c6e207.png)
