### ISSUE TITLE
e2e test and error

### ISSUE THREAD

**Issue by pietrzakadrian** [NarHakobyan/awesome-nest-boilerplate#16]
When I want to check e2e tests, I have this problem:

```
[Nest] 7345   - 2019-12-19 7:44:15 PM   [ExceptionHandler] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
[Nest] 7345   - 2019-12-19 7:44:18 PM   [ExceptionHandler] Unable to connect to the database. Retrying (2)... +3007ms
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

It is true that I have an external postgresql address and not localhost, but this should probably not be a problem?

**Comment by NarHakobyan** [comment]
e2e test not yet integrated. I need to find free time to do that, or if you can feel free to fork and open pull-request :)

**Comment by pietrzakadrian** [comment]
Could I ask you to do this as soon as you find time?
I am doing this project for my studies and e2e tests are required.

Thanks! :)

**Comment by pietrzakadrian** [comment]
@NarHakobyan I would still ask you to write unit and e2e tests. thank u:)

**Comment by antennaio** [comment]
There are a few improvements in this pull request https://github.com/NarHakobyan/awesome-nest-boilerplate/pull/79 :)
