### ISSUE TITLE
npm run debug:dev  error 

### ISSUE THREAD

**Issue by chenguzhen87** [NarHakobyan/awesome-nest-boilerplate#20]
![image](https://user-images.githubusercontent.com/28331609/75949594-b70daa00-5ee1-11ea-9eda-37b5c44ea771.png)
How to solve this error ?

**Comment by NarHakobyan** [comment]
Can't reproduce this issue

**Comment by chenguzhen87** [comment]
Under windows, running 'npm run debug: dev','TS_NODE_CACHE'is neither an internal or external command nor a runnable programOr batch file.
 After I try to remove the TS_NODE_CACHE, I can start normally

**Comment by NarHakobyan** [comment]
I have added cross-env, so you can pull and use on windows
