### ISSUE TITLE
@Body() don't transfer body object to dto object

### ISSUE THREAD

**Issue by chenguzhen87** [NarHakobyan/awesome-nest-boilerplate#21]
![image](https://user-images.githubusercontent.com/28331609/76330702-23950880-6329-11ea-8f0a-78964ce9f32d.png)

**Comment by NarHakobyan** [comment]
Hi @chenguzhen87, I have chacked and it's working

**Comment by osmanraifgunes** [comment]
`    @Post('update')
    @Roles(RoleType.ADMIN)
    @HttpCode(HttpStatus.OK)
    @ApiResponse({
        status: HttpStatus.OK,
        description: 'Edit user',
        type: UserDto,
    })
    updateUser(@Body() userDto: UserDto): Promise<UserEntity> {
        return this._userService.updateUser(userDto);
    }`

same here

**Comment by NarHakobyan** [comment]
@osmanraifgunes @chenguzhen87 body always needs to be validated, without that it will not convert to class, use class-validator decorators to do that.

for example 
```typescript
class UserDto {
@IsString()
readonly username: string;
@IsString()
readonly password: string;
}
```

**Comment by osmanraifgunes** [comment]
I need some nullable areas and @IsString() is forcing me to not-null values.

**Comment by NarHakobyan** [comment]
@osmanraifgunes use `@IsOptional()` decorator.

you can find more here 

https://github.com/typestack/class-validator
