### ISSUE TITLE
How to map entities to DTOs and vice-versa 

### ISSUE THREAD

**Issue by MidoAhmed** [NarHakobyan/awesome-nest-boilerplate#23]
What is the best way to map database entities to DTO's in NestJs  and vice-versa ?
what about class-transformer OR, there is a popular automapper package (automapper-ts) ?

**Comment by NarHakobyan** [comment]
Hi @MidoAhmed, if your Entity extends from AbstractEntity you can call `entity.toDto()` or if you have array of entities `entities.toDtos()`

**Comment by MidoAhmed** [comment]
Hi @NarHakobyan thanks for your quick reply, so my entity extends from BaseEntity !

**Comment by NarHakobyan** [comment]
@MidoAhmed If you are using this boilerplate then tou need to extend from AbstractEntity and use repositories to save or get data

**Comment by MidoAhmed** [comment]
@NarHakobyan i'm not using it but, I saw your method and I have googled that and I found there those who recommend class-transformer so i am lost which one is better if u can explain the differences and benefits.
