### ISSUE TITLE
/documentation works on dev but doesnot work on production 

### ISSUE THREAD

**Issue by hkarimpoor** [NarHakobyan/awesome-nest-boilerplate#25]
http://localhost:3000/documentation  url works well and return proper  api document page but when project is deployed to host ,  http://www.example.com/documentation  return 404

**Comment by NarHakobyan** [comment]
Yes because it's for development purposes.

**Comment by NarHakobyan** [comment]
```dart
    if (['development', 'staging'].includes(configService.nodeEnv)) {
        setupSwagger(app);
    }
```

it's available in the development and staging environments. so if you want to have documentation in server deploy it to staging env instead of production

**Comment by hkarimpoor** [comment]
I need to make /documentation accessible  on production but under Admin rule access , first of all I tried below : 
`/* if (['development', 'staging'].includes(configService.nodeEnv)) {
        `setupSwagger(app);`
    }*/`
`setupSwagger(app);`

To force make it accessible for all environment but still work on only dev 
Any suggestion to implement this approach ?

**Comment by hkarimpoor** [comment]
I mean I commented the condition and put setupSwagger  method out of condition

**Comment by NarHakobyan** [comment]
I just tried both ways, commenting code and adding production and both working nice.

```dart
    if (['development', 'staging', 'production'].includes(configService.nodeEnv)) {
        setupSwagger(app);
    }
```

**Comment by hkarimpoor** [comment]
> I just tried both ways, commenting code and adding production and both working nice.
> 
> ```dart
>     if (['development', 'staging', 'production'].includes(configService.nodeEnv)) {
>         setupSwagger(app);
>     }
> ```
