### ISSUE TITLE
Update Nest 6 to 7 and project dependencies 

### ISSUE THREAD

**Issue by pedrolucasoliva** [NarHakobyan/awesome-nest-boilerplate#26]
Update Nest 6 to 7 and project dependencies of project to the last versions.

**Comment by pedrolucasoliva** [comment]
@NarHakobyan, we did the same thing at the same time? lol

**Comment by NarHakobyan** [comment]
you did more them me :D

**Comment by pedrolucasoliva** [comment]
Tomorrow I will solve the conflicts. Nice project @NarHakobyan. Thanks a lot. Maybe I did a Angular front to this backend.

**Comment by NarHakobyan** [comment]
Good idea, also I want to create microservices and move dto to separate package, so front-end also can use them
