### ISSUE TITLE
Investigate MikroOrm

### ISSUE THREAD

**Issue by NarHakobyan** [NarHakobyan/awesome-nest-boilerplate#276]
https://docs.nestjs.com/recipes/mikroorm

**Comment by vanenshi** [comment]
take a look at the https://docs.nestjs.com/recipes/prisma
I was planning to create a fork of your boilerplate with `prisma`

https://www.prisma.io/docs/concepts/more/comparisons/prisma-and-typeorm

**Comment by NarHakobyan** [comment]
Hi @vanenshi, Thanks for your suggestion, I'm not familiar with prisma, could you please guide how to use it for complex queries like using subqueries, postgres triggers, and write custom sql code.

**Comment by JustDenP** [comment]
In my little experience Prisma is great for small projects (blog, simple services, etc), it's also a great solution inside NeXtjs if you use it as small backend, but for complex solutions it's not very handy. Maintaining a large number of entities in one file becomes very difficult.

Mikrorm is similar to TypeORM though and you can use the same development principles in Nestjs as with TypeORM, so migration should not be very difficult. So I think it's a good choice

**Comment by vanenshi** [comment]
@JustDenP Thanks denis
I guess I'll try mikroOrm
