### ISSUE TITLE
is typeorm working?

### ISSUE THREAD

**Issue by ks221197** [NarHakobyan/awesome-nest-boilerplate#279]
- nestjs/typeorm@9.0.0
- typeorm@0.3.7
- node@14.19.3
- npm@6.14.17

 
error TS2305: Module '"typeorm"' has no exported member 'FindConditions'.
 
[Nest] 21204  - 18/07/2022, 11:22:49   ERROR [ExceptionsHandler] No metadata for "UserRepository" was found.
EntityMetadataNotFoundError: No metadata for "UserRepository" was found.

**Comment by NarHakobyan** [comment]
typeorm 0.3 has a lot of breaking changes. so almost anything got broken
