### ISSUE TITLE
 yarn build:prod fail

### ISSUE THREAD

**Issue by roshanneotech** [NarHakobyan/awesome-nest-boilerplate#282]
Hi,
I am trying to run command  yarn build:prod and it is giving me following error. Can anyone suggest what changes I need to do to resolve this issue

`src/validators/exists.validator.ts:9:29 - error TS2305: Module '"typeorm"' has no exported member 'FindConditions'.

9 import type { EntitySchema, FindConditions, ObjectType } from 'typeorm';
                              ~~~~~~~~~~~~~~

src/validators/unique.validator.ts:9:29 - error TS2305: Module '"typeorm"' has no exported member 'FindConditions'.

9 import type { EntitySchema, FindConditions, ObjectType } from 'typeorm';
                              ~~~~~~~~~~~~~~

Found 3 errors in 3 files.

Errors  Files
     1  node_modules/typeorm-seeding/dist/connection.d.ts:13
     1  src/validators/exists.validator.ts:9
     1  src/validators/unique.validator.ts:9
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Also when building docker images it is giving aurora db driver error
` => ERROR [dist 5/5] RUN yarn build:prod                                                                          37.5s
------
 > [dist 5/5] RUN yarn build:prod:
#11 1.432 yarn run v1.22.19
#11 1.482 $ tsc -p tsconfig.build.json
#11 37.38 node_modules/typeorm-seeding/dist/connection.d.ts(13,1211): error TS2307: Cannot find module 'typeorm/driver/aurora-data-api/AuroraDataApiConnectionOptions' or its corresponding type declarations.`

**Comment by NarHakobyan** [comment]
Fixed :)

**Comment by omattman** [comment]
I believe this fix introduced new errors. Getting errors in those files you edited @NarHakobyan

**Comment by omattman** [comment]
For reference: https://github.com/NarHakobyan/awesome-nest-boilerplate/issues/283
