### ISSUE TITLE
Function passing param error

### ISSUE THREAD

**Issue by Mahoo12138** [NarHakobyan/awesome-nest-boilerplate#289]
Is it may save the `postEntity` not the `updatePostDto` ?
https://github.com/NarHakobyan/awesome-nest-boilerplate/blob/2911bdac33a4305efce78b0cec2b5d5670832f22/src/modules/post/post.service.ts#L59-L71

**Comment by NarHakobyan** [comment]
@Mahoo12138 Use Discussions.
