### ISSUE TITLE
Linter Errors

### ISSUE THREAD

**Issue by Be-P** [NarHakobyan/awesome-nest-boilerplate#290]
Hi Nar! Thank you for sharing this amazing boilerplate. 

I was running `yarn lint` and I was getting back many errors, many of them are:
 - value is always truthy
 - chain on a non-nullish value
 - Unnecessary conditional
 - Filename is not in kebab case

Is it my fault, or is it to be fixed? 
If you tell me how to fix it I'll be glad to make a PR to help you out

**Comment by NarHakobyan** [comment]
Hi @Be-P, thanks for the report, We've updated linter file, so will fix all the issues ASAP.
