### ISSUE TITLE
Run  migration:generate not work!

### ISSUE THREAD

**Issue by iafine** [NarHakobyan/awesome-nest-boilerplate#291]
When I run `yarn  migration:generate xxx`, It not work, and look like is a typeorm cli arguments problem.

```
typeorm version : 0.3.9
```
Error detail:
```
Not enough non-option arguments: got 0, need at least 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-typeorm@0.0.1 typeorm: `ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --config src/ormconfig.ts "entity:create" "-n" "user"`      
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-typeorm@0.0.1 typeorm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hamja\AppData\Roaming\npm-cache\_logs\2022-03-27T06_06_50_058Z-debug.log
```

**Comment by JeremyXIonia** [comment]
I had the same problem

**Comment by gongzili456** [comment]
I had the same problem, How to resolve it?

**Comment by NarHakobyan** [comment]
Hi Guys, typeorm changes migration generate command, use full path instead of naem, `yarn migration:generate src/database/migrations/[name]`

**Comment by Miofly** [comment]
this question in main branch remains

**Comment by Miofly** [comment]
> Hi Guys, typeorm changes migration generate command, use full path instead of naem, `yarn migration:generate src/database/migrations/[name]`


this question in main branch remains
