### ISSUE TITLE
Remote repository

### ISSUE THREAD

**Issue by mso1985** [NarHakobyan/awesome-nest-boilerplate#30]
Hi, can you point me in the right direction to add remote repository other than typeorm. I want to create an entity and fetch data from another non-nestjs api.  I would like to use pageDtos like userEntity.

Thnks

**Comment by NarHakobyan** [comment]
Hi, do you want to use 3rd party API or connect to another database?

**Comment by mso1985** [comment]
3rd party API

**Comment by NarHakobyan** [comment]
create a shared module for that, under it create service, and wrap your API under that, and in other places just import that module and use it
