### ISSUE TITLE
Error when using pagination and specify column select

### ISSUE THREAD

**Issue by tinnt-developer** [NarHakobyan/awesome-nest-boilerplate#303]
const [items, pageMetaDto] = await this.analyticsRepository
      .createQueryBuilder('demo')
      .select('date')
      .paginate(queryRequest);
I got this error when using the above code with the case of specifying the column to select, do you have any solution to fix this problem? thank you very much.
error:
at Reflect.getMetadata (/Users/a/node_modules/reflect-metadata/Reflect.js:354:23)
    at SelectQueryBuilder.typeorm_1.SelectQueryBuilder.paginate (/Users/a/x/src/boilerplate.polyfill.ts:220:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AdsService.getAnalytics (/Users/a/x/src/modules/ads/ads.service.ts:355:34)

**Comment by SaadBazaz** [comment]
Same error!

**Comment by SaadBazaz** [comment]
So I found a quick fix for this. 
On my end, in this file and line -> https://github.com/NarHakobyan/awesome-nest-boilerplate/blob/main/src/boilerplate.polyfill.ts#L218

I had to change the line from:
```
    const entity = entities.find((item) => item.id === id) as AbstractEntity;
```

to

```
    const entity = entities.find((item) => item.id == id) as AbstractEntity;
```

**Comment by NarHakobyan** [comment]
Hey everyone, without selecting `id` column it's not possible to paginate, as @SaadBazaz mentioned current version of paginate function maps rows by id.
