### ISSUE TITLE
Can I use mongodb?

### ISSUE THREAD

**Issue by mbvb1223** [NarHakobyan/awesome-nest-boilerplate#31]
Heelooo, 

I am investigating this boilerplate for my project.
I want to use mongodb.
From my understanding, I think I need to install mongodb driver and enjoin it because this boilerplate is using typeorm: `npm install mongodb --save` https://typeorm.io/#/. Is it correct?

If it is correct, I think we should change `env file`
```
POSTGRES_HOST=clound.mongodb.com
POSTGRES_PORT=2710
POSTGRES_USERNAME=root
POSTGRES_PASSWORD=70GlDDVxbHEMllM6
POSTGRES_DATABASE=nestjs
```
To
```
DB_HOST=clound.mongodb.com
DB_PORT=2710
DB_USERNAME=root
DB_PASSWORD=70GlDDVxbHEMllM6
DB_DATABASE=nestjs
```

**Comment by mbvb1223** [comment]
does anyone here?

**Comment by NarHakobyan** [comment]
Use mongodb with typeorm
https://github.com/typeorm/typeorm/blob/master/docs/mongodb.md
