### ISSUE TITLE
ERROR [ExceptionsHandler] No metadata for "UserEntity" was found.

### ISSUE THREAD

**Issue by imfaisii** [NarHakobyan/awesome-nest-boilerplate#311]
I am facing this issue for quite a long time on windows. It works fine on ubuntu but gives this error on windows.
I have deleted ormConfig.ts and serving the project with npm run watch:dev

api-config.service.ts

  get sqlConfig(): TypeOrmModuleOptions {
    let entities = [
      __dirname + '/../../modules/**/*.entity{.ts,.js}',
      __dirname + '/../../modules/**/*.view-entity{.ts,.js}',
    ];

**Comment by Secret1007** [comment]
hey,bro,how did u solve this?
