### ISSUE TITLE
[Feature Request] Add logging with verbosity levels

### ISSUE THREAD

**Issue by SaadBazaz** [NarHakobyan/awesome-nest-boilerplate#312]
Hey,
Using this to build an awesome backend.
One thing which always irks me; most frameworks don't have DB level logs by default. You have to write em yourself. 

If we could somehow inject NestJS's Logger at DB level, and control it via verbosity (i.e. VERBOSITY=['db', 'controllers'], etc) that would be truly awesome. Good for quick debugging.

**Comment by NarHakobyan** [comment]
Hey, but it has a logs for DB 

<img width="447" alt="image" src="https://github.com/NarHakobyan/awesome-nest-boilerplate/assets/1781506/2c79508b-f917-4d18-8f92-024c614d5ada">
