### ISSUE TITLE
Project runs but is not being served 

### ISSUE THREAD

**Issue by NathanDowner** [NarHakobyan/awesome-nest-boilerplate#319]
The `server running on` message doesn't get printed to the console and the project isn't being served from the port I specified in my `.env` file, if it's being served at all (I can't find it).  I do however see the printout of the different dependencies (modules being loaded).

I've also followed the steps for setup but I'm wondering if there's something I need to edit.

[Here's a link to my sample project](https://github.com/NathanDowner/test-awesome-nestjs-template) based on the template. I've changed nothing. I'd be happy for any assistance

**Comment by moinul192000** [comment]
I tried to run your sample project on codespace and it seems working fine. Might be related to your environment, can you try different environment?
