### ISSUE TITLE
 `yarn eslint` reports 96 problems (65 errors, 31 warnings)

### ISSUE THREAD

**Issue by mbvb1223** [NarHakobyan/awesome-nest-boilerplate#33]
![image](https://user-images.githubusercontent.com/11681514/84846598-5877d080-b079-11ea-9121-f90394239594.png)

1. When I run `yarn eslint`, the system will report as image above.

-------------

2. I want to add a new file `src/modules/math/math.controller.spec.ts` but I could not commit it 

```
✖ eslint --fix found some errors. Please fix them and try committing again.		
var/www/html/awesome-nest-boilerplate/src/modules/math/math.controller.spec.ts
0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src/modules/math/math.controller.spec.ts.
The file must be included in at least one of the projects provided
				
✖ 1 problem (1 error, 0 warnings)
husky > pre-commit hook failed (add --no-verify to bypass)
```
I see in tsconfig.json, we are excluding `**/*.spec.ts` files

---
I am reading and searching more about this but I want to ask: `are they issues of this boilerplate?`

**Comment by NarHakobyan** [comment]
Fixed all linter rules and parser error
