### ISSUE TITLE
 ERROR [ExceptionsHandler] You need to use @UseDto on class (ClassNameEntity) be able to call toDto function

### ISSUE THREAD

**Issue by tinnt-uranus** [NarHakobyan/awesome-nest-boilerplate#332]
// use-dto.decorator.ts

```
import { type Constructor } from '../types';

export function UseDto(dtoClass: Constructor): ClassDecorator {
  return (ctor) => {
    // FIXME make dtoClass function returning dto

    if (!(<unknown>dtoClass)) {
      throw new Error('UseDto decorator requires dtoClass');
    }

    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
    ctor.prototype.dtoClass = dtoClass;
  };
}
```

The ctor.prototype.dtoClass  always undefined.

**Comment by KoudouMax** [comment]
use Reflect metadata.
// use-dto-decorator.ts
export const DTO_KEY = Symbol('DTO_KEY');

export function UseDto(dto: Constructor): ClassDecorator {
  // eslint-disable-next-line @typescript-eslint/ban-types
  return (target: Function) => {
    Reflect.defineMetadata(DTO_KEY, dto, target);
  };
}

//abtract.entity.ts
toDto(options?: O): DTO {
    const DtoClass = Reflect.getMetadata(DTO_KEY, this.constructor);

    if (!DtoClass) {
      throw new Error(
        `You need to use @UseDto on class (${this.constructor.name}) be able to call toDto function`,
      );
    }

    return new DtoClass(this, options);
  }

**Comment by tuancao-mti** [comment]
Actual, we don't need to define `private dtoClass?: Constructor<DTO, [AbstractEntity, O?]>;` in abstract.entity.ts. Just remove it and make a change in `toDto` method.
`toDto(options?: O): DTO {
    const dtoClass = Object.getPrototypeOf(this).dtoClass;

    if (!dtoClass) {
      throw new Error(
        `You need to use @UseDto on class (${this.constructor.name}) be able to call toDto function`,
      );
    }

    return new dtoClass(this, options);
  }`
