### ISSUE TITLE
reflect-metadata version issue

### ISSUE THREAD

**Issue by Monstermash28425R1** [NarHakobyan/awesome-nest-boilerplate#348]
i just clone the repo and try to install the dependencies and i ran into a issue:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: awesome-nestjs-boilerplate@10.0.0
npm ERR! Found: reflect-metadata@0.2.1
npm ERR! node_modules/reflect-metadata
npm ERR!   reflect-metadata@"^0.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer reflect-metadata@"^0.1.12" from @nestjs/common@10.3.0
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/monster/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/monster/.npm/_logs/2024-04-10T20_19_41_047Z-debug-0.log

either way i try to install different versions of that package but yet can fix the issue, im using node LTS 20 btw

**Comment by NarHakobyan** [comment]
Maybe you have internet connection issues.
