### ISSUE TITLE
Could not resolve reference: #/components/schemas/

### ISSUE THREAD

**Issue by nvthuong1996** [NarHakobyan/awesome-nest-boilerplate#36]
I setup and run success boilerplate. but when i access swagger a error append 👎 

```
Could not resolve reference: #/components/schemas/

```

How i resolve it ?

**Comment by NarHakobyan** [comment]
Hi dear @nvthuong1996,

it's working very well, maybe you are accessing documentation with a wrong URL. try https://localhost:3000/documentation

**Comment by nvthuong1996** [comment]
i access http://localhost:3000/documentation =>  after click vào register api => error append.

**Comment by NarHakobyan** [comment]
it's related to nest/swagger lib, https://github.com/nestjs/swagger/issues/669

**Comment by nvthuong1996** [comment]
have other way resolve this proplem ?

**Comment by NarHakobyan** [comment]
you can remove file api decorator

**Comment by nvthuong1996** [comment]
i already try. thank you
