### ISSUE TITLE
Filtering data by user

### ISSUE THREAD

**Issue by mso1985** [NarHakobyan/awesome-nest-boilerplate#38]
say you have a new entity you want to list.. wich will be the best way of filtering by logged user id? interceptor would be the best choice right?

**Comment by NarHakobyan** [comment]
Hi @mso1985, You can get logged in user by @AuthUser decorator and pass to your service function as options (options always need to be Partial)

```typescript
    @Get('users')
    @Roles(RoleType.USER)
    @HttpCode(HttpStatus.OK)
    async admin(@AuthUser() currentUser: UserEntity) {
        const userEntities = await this.yourService.getUsers({parentId: currentUser.id});
    }
```

**Comment by mso1985** [comment]
Great! this boilerplate is proving itself
