### ISSUE TITLE
UUID Validation

### ISSUE THREAD

**Issue by bin4ryio** [NarHakobyan/awesome-nest-boilerplate#4]
Hey! Thanks for the great boilerplate. I'd like to know how do you handle UUID validation on a controller params.

Do you create a new xxxDto file for say, getPostDto?

**Comment by NarHakobyan** [comment]
Hi @bin4ryio.

yes we are creating separate dto files for body and query params and using @IsUUID(version?: "3"|"4"|"5") decorator to validate UUID. example

```typescript
export class PostPageOptionsDto {
  @ApiModelProperty()
  @IsUUID()
  readonly postId: string;
}
...
  @Get('posts')
  getPosts(
    @Query(new ValidationPipe({ transform: true }))
      pageOptionsDto: PostPageOptionsDto,
  ): Promise<PostPageDto> {
    return this.postService.getPosts(pageOptionsDto);
  }

```

**Comment by bin4ryio** [comment]
That certainly helps! Do you mind sharing your .services.ts with find, findAll, post as well? I am just trying to see if my practices for the CRUD fit.

**Comment by NarHakobyan** [comment]
Glad to help, I will add service this weekend ;)
