### ISSUE TITLE
How to use nanoid instead of uuid for entitiy ids

### ISSUE THREAD

**Issue by geongeorge** [NarHakobyan/awesome-nest-boilerplate#40]
I know this is not directly related to this boilerplate but for the love of God I cannot find how to do this.

I tried to achieve this using the default attribute:
```ts
@PrimaryColumn({ length: 21, default: () => `'${nanoid()}'` })
    id: string;
```

But this causes issues when using the second has the same duplicate key.

Please at least point where to look before closing this issue.

Thanks

**Comment by geongeorge** [comment]
I found a solution at last:

```ts

   @PrimaryColumn({ length: 21 })
    id: string;

    @BeforeInsert()
    generateUuid() {
        this.id = nanoid();
    }

```

I'm open if there are better solutions.

**Comment by NarHakobyan** [comment]
Hi @geongeorge, yes your solution will work, but we prefer to use Postgres level default values, instead of UUID you can use hash_encode/hash_decode https://hashids.org/postgresql

**Comment by geongeorge** [comment]
Thank you @NarHakobyan , I'm not sure how to use this with our system.
Does this mean we use a default `PrimaryGeneratedColumn()` (incremental numbers) and use a `hash_encode` when taking as output?

**Comment by NarHakobyan** [comment]
@geongeorge no, you need to use PrimaryColumn() with hash_encode, but we always using UUIDs
