### ISSUE TITLE
Generate modules in the modules folder

### ISSUE THREAD

**Issue by Dragoncall** [NarHakobyan/awesome-nest-boilerplate#53]
I am not really experienced with the nest framework nor boilerplates, yet, I think that, as explained in the docs, modules should be under the `modules` folder. Currently, generating a module with the nest-cli puts it in the `src` folder.

Would it be possible to generate these modules in the modules folder directly?

**Comment by kungfu321** [comment]
Just add folder to the path like this: `nest g mo modules/tasks`
