### ISSUE TITLE
How to work on development with docker

### ISSUE THREAD

**Issue by kungfu321** [NarHakobyan/awesome-nest-boilerplate#54]
Thanks for the awesome project
But how to work on development, because Dockerfile seem for production
Thanks

**Comment by NarHakobyan** [comment]
Hi @kungfu321, I agree it takes time to do development using Docker. Here is the workflow which you can use for fast development.

1. Install Postgres to your local machine or use docker image with an exposed port
2. Run `yarn watch:dev`
3. Use swagger documentation to run queries (https://localhost:300/documentation)
