### ISSUE TITLE
error Command "build" not found - package.json doesn't have build command

### ISSUE THREAD

**Issue by jaybabak** [NarHakobyan/awesome-nest-boilerplate#55]
Tried to set this up locally but ran into this odd issue, after looking at the Docker file I can see yarn build attempted to be run but it is not part of the package.json file, how should I proceed?

**Comment by aklen** [comment]
I had the same problem!

There are two solutions:
1. Overwrite line 8 in Dockerfile from
```
RUN yarn build
```
to
```
RUN yarn build:prod
```

2. Or create a new command in package.json's "scripts" section
```
"scripts": {
    "build": "tsc -p tsconfig.build.json",
    "build-prod": "tsc -p tsconfig.build.json",
    ....
}
```
