### ISSUE TITLE
nestjsx, model generator and multi-tenant

### ISSUE THREAD

**Issue by mbnoimi** [NarHakobyan/awesome-nest-boilerplate#56]
Hi,

Have you considered adding these features to this fabulous boilerplate?
1. CRUD: https://github.com/nestjsx/crud
2. Model generator: https://github.com/Kononnable/typeorm-model-generator
3. Multi-tenacy : https://github.com/AlexanderC/nestjs-mtenant

**Comment by NarHakobyan** [comment]
Hi @mbnoimi,

Thanks for your suggestion, I will take a look on it. 🙋‍♂️

**Comment by afilp** [comment]
Also interested to this, thanks a lot!

**Comment by NarHakobyan** [comment]
Hi guys, do you have some best practice repos or documentations?
