### ISSUE TITLE
How to create an admin user ❓ 

### ISSUE THREAD

**Issue by dorettoartesp** [NarHakobyan/awesome-nest-boilerplate#63]
How to create an admin user ?

Thanks in advance.

**Comment by NarHakobyan** [comment]
@dorettoartesp Hi, what you mean by saying `admin user`?

**Comment by dorettoartesp** [comment]
A user with role = "ADMIN" instead of "USER". 👍

**Comment by NarHakobyan** [comment]
Just create a user with role="ADMIN"
