### ISSUE TITLE
New feature: MongoDB integration

### ISSUE THREAD

**Issue by KimKiHyuk** [NarHakobyan/awesome-nest-boilerplate#66]
Hello there :) 

how do you think about adding mongodb integration with mongoose? 

if you ok, I'm going to work on it

also mongo backend coding pattern(interact with dto, controller, service, repository pattern) will be 100% same like postgresql backend

**Comment by NarHakobyan** [comment]
Hey @KimKiHyuk, what about using typeorm for mongodb? I didn't try it but maybe you can give a try and send us feedback about it :D

https://typeorm.io/#/mongodb

**Comment by KimKiHyuk** [comment]
Thanks for your reply :)

Unfortunately, I'm familiar with Mongoose, and have experience nest.js + mongoose  

also when comparing TypeOrm with mongoose, I feel mongoose more robust than TypeOrm. 

As docs https://typeorm.io/#/mongodb  mentioned,
```
TypeORM has basic MongoDB support. Most of TypeORM functionality is RDBMS-specific, this page contains all MongoDB-specific functionality documentation.
```

TypeOrm was born to be SQL base system, so it has only basic functionality for mongo but  mongoose was born to be mongo and it has many features

**Comment by NarHakobyan** [comment]
@KimKiHyuk thanks for your message, we can plan to do that after having cli tool for generating boilerplate code, so we can make mongoose or typeorm as options

**Comment by KimKiHyuk** [comment]
Good! I have every intention of building mongoose boilerplate. 

please let me know if you need it :)

**Comment by NarHakobyan** [comment]
Nice :), let’s keep this issue opened so we can come back to this topic again

**Comment by quanghd-blueotter** [comment]
any update?

**Comment by NarHakobyan** [comment]
@quanghd-blueotter [typeorm supports mongodb](https://orkhan.gitbook.io/typeorm/docs/mongodb) out of hood, this issue is not actual anymore. Closing.
