### ISSUE TITLE
GetConstructorArgs Type

### ISSUE THREAD

**Issue by DJEDAINI** [NarHakobyan/awesome-nest-boilerplate#69]
When i tried to generate migration from Database using this commnad: **npm run migration:generate -n Users**
i got this issue:
Error during migration generation:

src/providers/utils.provider.ts:12:38 - error TS2304: Cannot find name 'GetConstructorArgs'.
12     model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,

src/providers/utils.provider.ts:14:15 - error TS2304: Cannot find name 'GetConstructorArgs'.
14     options?: GetConstructorArgs<T>[1],

src/providers/utils.provider.ts:17:38 - error TS2304: Cannot find name 'GetConstructorArgs'.
17     model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,

src/providers/utils.provider.ts:19:15 - error TS2304: Cannot find name 'GetConstructorArgs'.
19     options?: GetConstructorArgs<T>[1],

src/providers/utils.provider.ts:22:38 - error TS2304: Cannot find name 'GetConstructorArgs'.
22     model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,

src/providers/utils.provider.ts:24:15 - error TS2304: Cannot find name 'GetConstructorArgs'.
24     options?: GetConstructorArgs<T>[1],

**Comment by tolstenko** [comment]
I am facing the same thing. I guess this problem started with this commit. It is when the refractor happened https://github.com/NarHakobyan/awesome-nest-boilerplate/commit/efc49488c8fdb68251fef093a8e386137e30f15b

**Comment by NarHakobyan** [comment]
Hi guys, I will take a look on it today, and give you an update

**Comment by NarHakobyan** [comment]
Hi guys, I will take a look on it today, and give you an update

**Comment by NarHakobyan** [comment]
@tolstenko @DJEDAINI, I've pushed fix for this issue, so you can rebase from your side too, also instead of running `npm run migration:generate -n [NAME]` use `yarn migration:generate [NAME]` or `npm run migration:generate [NAME]`
