### ISSUE TITLE
Property 'dtoClass' in type 'ResultEntity' is not assignable to the same property in base type 'AbstractEntity<ResultResponseDto>'.

### ISSUE THREAD

**Issue by LuwanKonnect** [NarHakobyan/awesome-nest-boilerplate#78]
https://stackoverflow.com/questions/66011742/the-child-entity-is-incompatible-with-the-base-entity-typescript
when I try write a module 'Result' use this boilerplate, I face same error with the link above.
I find that the userEntity and user-dto can work with no error, but when I try use format like the user, I got the error.
```
Property 'dtoClass' in type 'ResultEntity' is not assignable to the same property in base type 'AbstractEntity<ResultResponseDto>'.
  Type 'ResultResponseDto' is not assignable to type 'new (entity: AbstractEntity<AbstractDto>, options?: never) => ResultResponseDto'.
    Type 'ResultResponseDto' provides no match for the signature 'new (entity: AbstractEntity<AbstractDto>, options?: never): ResultResponseDto'.
```

my ResultEntity looks like. 
```
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { AbstractEntity } from '../../common/abstract.entity';
import { ResultResponseDto } from './dto/resultResponse.dto';

@Entity('result')
export class ResultEntity extends AbstractEntity<ResultResponseDto> {
// export class ResultEntity {
  @Column()
  email: string;
  @Column()
  name: string;
  @Column()
  fileAddress: string;
  @Column()
  receiptAddress: string;
  @Column()
  searchNumber: string;
  @Column()
  certificate: string;

  dtoClass: ResultResponseDto;
}
```
then I got red line shows in dtoClass:  
```
Property 'dtoClass' in type 'ResultEntity' is not assignable to the same property in base type 'AbstractEntity<ResultResponseDto>'.
  Type 'ResultResponseDto' is not assignable to type 'new (entity: AbstractEntity<AbstractDto>, options?: never) => ResultResponseDto'.
    Type 'ResultResponseDto' provides no match for the signature 'new (entity: AbstractEntity<AbstractDto>, options?: never): ResultResponseDto'.ts(2416)
```
my ResultResponseDto are. 
```
import { ApiProperty } from '@nestjs/swagger';
import { IsEmail, IsNotEmpty, IsString } from 'class-validator';
import { AbstractDto } from '../../../common/dto/abstract.dto';
import { ResultEntity } from '../result.entity';

export class ResultResponseDto extends AbstractDto {
// export class ResultResponseDto {
  @ApiProperty({
    description: 'Email',
  })
  @IsEmail()
  @IsNotEmpty({ message: 'email cannot be empty' })
  @IsString({ message: 'the value must be a string' })
  email: string;

  @ApiProperty({
    description: 'name',
  })
  name: string;

  @ApiProperty({
    description: 'pdf file address',
  })
  fileAddress: string;

  @ApiProperty({
    description: 'receipt file address',
  })
  receiptAddress: string;

  @ApiProperty({
    description: 'search number',
  })
  searchNumber: string;

  @ApiProperty({
    description: 'certificate number',
  })
  certificate: string;

  constructor(result: ResultEntity) {
    super(result);
    this.email = result.email;
    this.name = result.name;
    this.certificate = result.certificate;
    this.fileAddress = result.fileAddress;
    this.receiptAddress = result.receiptAddress;
    this.searchNumber = result.searchNumber;
  }
}
```
then I got red line shows in 'super(result)' which shows
```
Argument of type 'ResultEntity' is not assignable to parameter of type 'AbstractEntity<AbstractDto>'.
  Types of property 'dtoClass' are incompatible.
    Type 'ResultResponseDto' is not assignable to type 'new (entity: AbstractEntity<AbstractDto>, options?: never) => AbstractDto'.
      Type 'ResultResponseDto' provides no match for the signature 'new (entity: AbstractEntity<AbstractDto>, options?: never): AbstractDto'.
```. 
May I ask why?

**Comment by NarHakobyan** [comment]
Hi @LuwanKonnect, change `dtoClass: ResultResponseDto;` to `dtoClass = ResultResponseDto;` AbstractDto need to have it's reference to create an instance when calling .toDto() method.

**Comment by LuwanKonnect** [comment]
Thanks for your response, I should check more carefully. Your plate is amazing, but I have a little bit confuse about this toDto part which also include line 11-28 in utils.provider.ts and the global function in boilerplate.polyfill.ts. I can guess the purpose of these function, but I have no idea why we can write like this. I try learning more online but didn't find something similar like this. Is it possible I get some keyword related to this. Anyway, still thanks for your help!

**Comment by NarHakobyan** [comment]
@LuwanKonnect it's very easy, databaseEntity.toDto() helps us easily convert entity to Dto and send it to client.

**Comment by LuwanKonnect** [comment]
Thanks for your response, I understand the toDto() is to convert to Dto, but I lack knowledge of why we can write code like that style, like the follow code 
```
  public static toDto<T, E>(
    model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,
    entity: E,
    options?: GetConstructorArgs<T>[1],
  ): T;
  public static toDto<T, E>(
    model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,
    entity: E[],
    options?: GetConstructorArgs<T>[1],
  ): T[];
  public static toDto<T, E>(
    model: new (entity: E, options?: GetConstructorArgs<T>[1]) => T,
    entity: E | E[],
    options?: GetConstructorArgs<T>[1],
  ): T | T[] {
    if (Array.isArray(entity)) {
      return entity.map((u) => new model(u, options));
    }

    return new model(entity, options);
  }
```
why the first three toDto()only have method name but no method body?   
Also I got a new issue.  
In user signUp, I use `@Body() signUpDto: SignUpDto,` to get body parameters, but I find that some parameters will loss, for example, if SignUpDto has 8 parameters, even I passed all to backend, the signUpDto only get 4 or 5. if I change to `@Body() signUpDto: any,` it will get all. The weird part is: I cannot get fullName in my project yesterday, then I change to `full` in SignUpDto, then I pass `full` not `fullName` through postman, I get it. After that, I change back to `fullName`, I can get it too. However, this method not work in my another project, and in this project I lost 4 parameters of 8. Do you have idea why this happens?

**Comment by NarHakobyan** [comment]
@LuwanKonnect, about the first question you can read [typescript's function overloading](https://www.typescriptlang.org/docs/handbook/2/functions.html#function-overloads).
About SignUpDto, you can't pass field without validating them, so I guess you miss to add validations.

**Comment by NarHakobyan** [comment]
if you have any question please use discussion section instead of issues.
